### PR TITLE
Fix ResourceLocationException errors

### PR DESCRIPTION
**Pull request by AnonymousHacker1279**
Fix `ResourceLocationException` errors on world load due to calling `ResourceLocation#withDefaultNamespace()` on already-namespaced dimension IDs. The solution was to simply replace the call with `parse()`.

Previously, this message would be logged when loading a world after using custom portals:
```
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:minecraft:overworld
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.assertValidPath(ResourceLocation.java:284) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.resources.ResourceLocation.withDefaultNamespace(ResourceLocation.java:60) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at TRANSFORMER/cpapireforged@1.0.10/net.kyrptonaught.customportalapi.portal.linking.DimensionalBlockPos.fromTag(DimensionalBlockPos.java:17) ~[cpapireforged-neo-1.21.1-1.0.10.jar%23329!/:1.0.10]
	at TRANSFORMER/cpapireforged@1.0.10/net.kyrptonaught.customportalapi.portal.linking.PortalLinkingStorage.fromNbt(PortalLinkingStorage.java:33) ~[cpapireforged-neo-1.21.1-1.0.10.jar%23329!/:1.0.10]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.DimensionDataStorage.readSavedData(DimensionDataStorage.java:71) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.DimensionDataStorage.get(DimensionDataStorage.java:58) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.storage.DimensionDataStorage.computeIfAbsent(DimensionDataStorage.java:44) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at TRANSFORMER/cpapireforged@1.0.10/net.kyrptonaught.customportalapi.CustomPortalsMod.onServerStart(CustomPortalsMod.java:68) ~[cpapireforged-neo-1.21.1-1.0.10.jar%23329!/:1.0.10]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.ConsumerEventHandler.invoke(ConsumerEventHandler.java:26) ~[bus-8.0.2.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:350) ~[bus-8.0.2.jar%2367!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:315) ~[bus-8.0.2.jar%2367!/:?]
	at TRANSFORMER/neoforge@21.1.66/net.neoforged.neoforge.server.ServerLifecycleHooks.handleServerStarted(ServerLifecycleHooks.java:114) ~[neoforge-21.1.66-universal.jar%23212!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:674) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[server-1.21.1-20240808.144430-srg.jar%23211!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

As can be seen, `minecraft:minecraft:overworld` is not an expected `ResourceLocation`.

### CODE REVIEW

**Comment by AzureDoom** [comment]
Sorry for the delay! Merging now and will release when I can here.

**Comment by AnonymousHacker1279** [comment]
No worries! I see the release has been posted to Curseforge, but it isn't on the maven yet. No rush, just wanted to let you know in case you weren't aware.

**Comment by AzureDoom** [comment]
My maven had changed its maven.azuredoom.com/mods now.
https://maven.azuredoom.com/#/mods/net/kyrptonaught/customportalapi/cpapireforged-neo-1.21.1/1.0.11

**Comment by AnonymousHacker1279** [comment]
I see, thanks!

**Pull request merged**
